-- Schema for SCP data

CREATE TABLE "OBJECT_TYPES" (
	"OBJECT_TYPE_ID"	INTEGER,
	"NAME"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("OBJECT_TYPE_ID")
);

CREATE TABLE "UNIVERSAL_FIELDS" (
	"LINK"	TEXT,
	"PAGE_ID"	TEXT,
	"CREATED_AT"	TEXT,
	"CREATOR"	TEXT,
	"URL"	TEXT,
	"OBJECT_TYPE_ID"	INTEGER NOT NULL,
	"DOMAIN"	TEXT,
	PRIMARY KEY("LINK"),
	FOREIGN KEY("OBJECT_TYPE_ID") REFERENCES "OBJECT_TYPES"("OBJECT_TYPE_ID")
);

CREATE TABLE "HISTORY" (
	"LINK"	TEXT,
	"AUTHOR"	TEXT,
	"AUTHOR_HREF"	TEXT,
	"COMMENT"	TEXT,
	"DATE"	TEXT,
	PRIMARY KEY("LINK","DATE"),
	CONSTRAINT "UNIVERSAL FK" FOREIGN KEY("LINK") REFERENCES "UNIVERSAL_FIELDS"("LINK")
);

CREATE TABLE "REFERENCES" (
	"PARENT_LINK"	TEXT,
	"CHILD_LINK"	TEXT,
	PRIMARY KEY("PARENT_LINK","CHILD_LINK"),
	CONSTRAINT "PARENT FK" FOREIGN KEY("PARENT_LINK") REFERENCES "UNIVERSAL_FIELDS"("LINK"),
	CONSTRAINT "CHILD FK" FOREIGN KEY("CHILD_LINK") REFERENCES "UNIVERSAL_FIELDS"("LINK")
);

CREATE TABLE "TAGS" (
	"TAG"	TEXT,
	"LINK"	TEXT,
	PRIMARY KEY("TAG","LINK"),
	CONSTRAINT "UNIVERSAL FK" FOREIGN KEY (LINK) REFERENCES "UNIVERSAL_FIELDS"("LINK")
);

CREATE TABLE "IMAGES" (
	"LINK"	TEXT,
	"IMAGE_URL"	TEXT,
	PRIMARY KEY("LINK","IMAGE_URL"),
	CONSTRAINT "UNIVERSAL FK" FOREIGN KEY("LINK") REFERENCES "UNIVERSAL_FIELDS"("LINK")
);

CREATE TABLE "GOI" (
	"LINK"	TEXT,
	"TITLE"	TEXT,
	"RATING"	INTEGER,
	"RAW_CONTENT"	TEXT,
	"RAW_SOURCE"	TEXT,
	PRIMARY KEY("LINK"),
	CONSTRAINT "UNIVERSAL FK" FOREIGN KEY("LINK") REFERENCES "UNIVERSAL_FIELDS"("LINK")
);


CREATE TABLE "HUBS" (
	"LINK"	TEXT,
	"TITLE"	TEXT,
	"RAW_CONTENT"	TEXT,
	PRIMARY KEY("LINK"),
	CONSTRAINT "UNIVERSAL FK" FOREIGN KEY("LINK") REFERENCES "UNIVERSAL_FIELDS"("LINK")
);

CREATE TABLE "ITEMS" (
	"LINK"	TEXT,
	"TITLE"	TEXT,
	"RATING"	INTEGER,
	"SCP"	TEXT,
	"SCP_NUMBER"	INTEGER,
	"SERIES"	TEXT,
	"RAW_CONTENT"	TEXT,
	"RAW_SOURCE"	TEXT,
	PRIMARY KEY("LINK"),
	CONSTRAINT "UNIVERSAL FK" FOREIGN KEY("LINK") REFERENCES "UNIVERSAL_FIELDS"("LINK")
);

CREATE TABLE "TALES" (
	"LINK"	TEXT,
	"TITLE"	TEXT,
	"RATING"	INTEGER,
	"YEAR"	INTEGER,
	"RAW_CONTENT"	TEXT,
	"RAW_SOURCE"	TEXT,
	PRIMARY KEY("LINK"),
	CONSTRAINT "UNIVERSAL FK" FOREIGN KEY("LINK") REFERENCES "UNIVERSAL_FIELDS"("LINK")
);
